### ISSUE TITLE
`KeyError` when calling read_oct_volume() for E2E format

### ISSUE THREAD

**Issue by polklin** [marksgraham/OCT-Converter#1]
Hello,
thanks for this nice repo ! I'm facing some troubles reading an E2E file. I followed the instructions by doing :
 
```python
from  file_io.e2e import E2E 
filepath = "pathToImage/test_file.E2E"
file = E2E(filepath)
oct_volumes = file.read_oct_volume() 
```
An error is raised line 148 in `e2e.py` though, because one of the `volume_string` key is not part of `volume_array_dict`. 

Here is the full error :
```bash
KeyError                 Traceback (most recent call last)
<ipython-input-20-3b5e0ad42b68> in <module>
----> 1 oct_volumes = file.read_oct_volume()

~/3rdparty/OCT-Converter/file_io/e2e.py in read_oct_volume(self)
    146                         raw_volume = list(map(self.read_custom_float, all_bits))
    147                         image = np.array(raw_volume).reshape(image_data.width, image_data.height)
--> 148                         image = 256 * pow(image, 1.0 / 2.4)
    149                         volume_string = '{}_{}_{}'.format(chunk.patient_id, chunk.study_id, chunk.series_id)
    150                         volume_array_dict[volume_string][int(chunk.slice_id / 2) - 1] = image

KeyError: '2031_3756_24070'
```

I'm not super familiar with E2E format, but I can share you the test image (it's too big to pass it via the present issue, even zipped).

Best reagrds

**Comment by marksgraham** [comment]
Hi there,
If you can send me an email (address on my profile) with some way of accessing the test image then I can take a look.

**Comment by marksgraham** [comment]
Hi,

The error occurs for two image slices. I've modified the code slightly so it doesn't try to save image slices that don't have a corresponding `volume string` in the `volume_array_dict`. The code runs fine and I get 7 volumes out of it. I'm not sure if this modification causes any useful information to be lost in the conversion process. Do you know what image data should be present in the `.e2e` file you supplied? If so it would be handy if you could run the new code and see if the output matches up to what you expect.

**Comment by polklin** [comment]
Hi @marksgraham,

thanks for your quick reply ! Unfortunately no I don't have these informations, but the volumes extracted look good. 
I'll use it as is for now and come back to you if I found any wraong behavior.
Cheers

**Comment by marksgraham** [comment]
Great, thanks!
