### ISSUE TITLE
Blueish fundus image from fda files

### ISSUE THREAD

**Issue by drombas** [marksgraham/OCT-Converter#104]
Hi, fundus images from fda files look blueish when plotted.

Have you encountered this before?

I believe it is a just matter of swapped red and blue axes. Would it make sense to fix it?

**Comment by Oli4** [comment]
This is mentioned in the uocte [documentation](https://bitbucket.org/uocte/uocte/wiki/Topcon%20File%20Format) as well. I think just switching the blue with the red channel is the way to go.

**Comment by marksgraham** [comment]
Hi,

The only .fda file I have for testing is so low quality that I didn't notice the colours are wrong! But yes, lets fix it!
