### ISSUE TITLE
It misses one Bscan for conversion

### ISSUE THREAD

**Issue by RezaRB** [marksgraham/OCT-Converter#11]
Awesome work,
Could you please handle the following issue too: 
It seems it misses one Bscan for conversion. For example, an E2E file with 31 b-scans is converted to 30 images.

**Comment by marksgraham** [comment]
Hi there,
Does this happen for every .e2e you try? I know @natwille1 is working on the .e2e code at the moment so it may be this is fixed when they make their PR.

**Comment by RezaRB** [comment]
I tried different samples, for me, it misses one B-scan for every .E2E file.

**Comment by natwille1** [comment]
I will submit a PR that will change the way the code stores/extracts the images.. it might help fix your issue. One thing you could look at in the meantime is appending all extracted images (numpy matrices) to a list and returning that once it's finished processing the OCT volume.. then you can check if you're at least getting all images then

**Comment by jhanvoxel** [comment]
Thanks for your awesome work!  It happened to all my examples, too. one B-scan for every .e2e file is missing. Is it fixed?

**Comment by marksgraham** [comment]
Hi @jhanvoxel @RezaRB ,
I currently don't have any .e2e data that I could use to test this issue. If you are able to share any of your (anonymised) data then I could take a look and try to solve this - would that be possible?

**Comment by RezaRB** [comment]
Dear Mark,
I can share with you a sample E2E data and also the original converted image files exported by the Heidelberg software system. 
E2E Sample and the Exported Bscans.rar


| 
| 
|  | 
E2E Sample and the Exported Bscans.rar


 |

 |

 |


Comparing with the original converted images, I could find 3 different bugs with your E2E class scripts, you can recheck them for confidence:1. Your code omits the final B-scan, and instead put the first B-scan as the end one. So, in the E2E file conversion process, it misses one B-scan every time.2. As you know, the Heidelberg imaging system performs a kind of image alignment, most likely based on the RPE layer segmentation, where you can find different B-scans located on the same base layer. Your E2E class script destroys this useful and important component which is very necessary for 3D analysis methods.3. B-scan image intensities are downgraded by 10-20 percent and should be corrected.
Thank you for your consideration.Looking forward to the modified version. If you do not mind, please send me the final version.
Best regards,Reza Rasti
Ph.D. in Biomedical Engineering,
Email: mr.r.rasti@ieee.org 

    On Thursday, September 17, 2020, 03:34:35 PM GMT+4:30, Mark Graham <notifications@github.com> wrote:  
 
 


Hi @jhanvoxel @RezaRB ,
I currently don't have any .e2e data that I could use to test this issue. If you are able to share any of your (anonymised) data then I could take a look and try to solve this - would that be possible?

**Comment by jhanvoxel** [comment]
> Hi @jhanvoxel @RezaRB ,
> I currently don't have any .e2e data that I could use to test this issue. If you are able to share any of your (anonymised) data then I could take a look and try to solve this - would that be possible?

Hi Mark,

I'm afraid that I could not share any e2e files I'm working on. Really sorry about that. I tried to figure out this question and I added ``` 
num_slices +=1``` after line 126 
https://github.com/marksgraham/OCT-Converter/blob/173890a0a89c0ff8ebd706dfaf945fd24e599f1e/oct_converter/readers/e2e.py#L126
Also modified ``` volume_array_dict[volume_string][int(chunk.slice_id / 2) ] = image``` at line 151https://github.com/marksgraham/OCT-Converter/blob/173890a0a89c0ff8ebd706dfaf945fd24e599f1e/oct_converter/readers/e2e.py#L151
And after modification, it worked well for me, all Bscans are extracted.  Thanks for your awesome work again. 

Jin

**Comment by marksgraham** [comment]
Hi @jhanvoxel @RezaRB 
I have finally got round to looking at this issue. I've made some changes to the code on the dev branch - it would be great if you could try them out on your data and let me know if they work
Thanks,
Mark

**Comment by marcoduering** [comment]
Hi! I had the same issue (one missing slice) and can confirm that this is fixed in the dev branch. Thanks!

**Comment by marksgraham** [comment]
Thanks marco, I've merged the dev into master and am going to consider this issue closed for now.
