### ISSUE TITLE
Resaving E2E files

### ISSUE THREAD

**Issue by benjaminralex** [marksgraham/OCT-Converter#116]
Hey Mark,

Quick question: for E2E and FDA files, is it possible to add information to the metadata and the resave the files in the original format?

Thanks!

**Comment by marksgraham** [comment]
Hi,

At the moment there aren't any methods that allow you to do this, but I think it should be doable. It's just a matter of creating a construct for the relevant field, e.g. [patient metadata](https://github.com/marksgraham/OCT-Converter/blob/47f76b877116b61844cea830a4b9e9a4db97e02d/oct_converter/readers/binary_structs/fda_binary.py#L82), building the dict a done in [this example](https://construct.readthedocs.io/en/latest/intro.html) and then writing over the relevant bits of the image. 

If you're interested in trying to get it working i can maybe help, let me know. I don't have access to any scanners so wouldn't be able to test if it had worked
