### ISSUE TITLE
Bioptigen error loading several frames per scan 

### ISSUE THREAD

**Issue by grodrguez3** [marksgraham/OCT-Converter#120]
I work with Bioptigen files and I noticed that when there are several frames per scan (i.e. dimensions (FramesPerScan,Scans,Ascan, depth), it does not load all the frames. It ends up returning an array of size (Scans,Ascan, depth). I have not seen any averaging done so far so I was wondering why/how this is happening? Thank you!

**Comment by marksgraham** [comment]
Hi,

Are you finding several oct volume objects returned? The reader loads a 4-D object with shape `(t, z, x, y)` and then returns `t` OCTVolume objects with size  `(z, x, y)`.  See here:
https://github.com/marksgraham/OCT-Converter/blob/56d9283a5a9a931b4a00cdf9b14fc76814161aeb/oct_converter/readers/boct.py#L99-L114

You should be able to access the 4D object through the `.vol` attribute of the `BOCT` object.
