### ISSUE TITLE
e2e file reading quantity problem

### ISSUE THREAD

**Issue by Jackiecs3** [marksgraham/OCT-Converter#126]
hi mark

I am not a pure software engineer, so it is relatively difficult to solve these problems. I hope you can help me.

I used this command（pip install git+https://github.com/marksgraham/OCT-Converter） to obtain the latest code
But when I read the e2e file, I found that the number of files was incorrect, and the actual number obtained was less than the expected number。

I uploaded the files I used.

My code content is as follows:

`import json

from oct_converter.readers import E2E
filepath = "data/01003-od.e2e"
file = E2E(filepath)
oct_volumes =  file.read_oct_volume()

for volume in oct_volumes:
    volume.peek(show_contours=True)  # plots a montage of the volume
    volume.save("{}_{}.png".format(volume.volume_id, volume.laterality))
    print(volume.sex)
    volume.sex = 'U'
    print(volume.sex)

fundus_images = (
    file.read_fundus_image()
)  # returns a list of all fundus images with additional metadata if available
for image in fundus_images:
    #plt.imshow(image.image)
    #plt.show()
    image.save("{}+{}.jpg".format(image.image_id, image.laterality))

metadata = file.read_all_metadata()
with open("metadata.json", "w") as outfile:
    outfile.write(json.dumps(metadata, indent=4))`

I obtained data：

<img width="282" alt="image" src="https://github.com/marksgraham/OCT-Converter/assets/149683436/c66cbff1-32bd-418f-b083-a1a144b06cb2">

**Comment by Jackiecs3** [comment]
> Hi there,
> 
> How many fundus/en-face images do you expect to be in the file? It looks like 6 are extracted.
> 
> BTW, I edited your post to remove the link to data in case the data is non-anonymised and shouldn't be in the public domain, but I have the link now so can take a look if needs be.

Hi mark，

I tried again a few times and found that this code didn't work. The bold part I added。

_**for volume in oct_volumes:
volume.peek(show_contours=True) # plots a montage of the volume
volume.save("{}_{}.png".format(volume.volume_id, volume.laterality))
print(volume.sex)
volume.sex = 'U'
print(volume.sex)**_

fundus_images = (
file.read_fundus_image()
) # returns a list of all fundus images with additional metadata if available
for image in fundus_images:
#plt.imshow(image.image)
#plt.show()
image.save("{}+{}.jpg".format(image.image_id, image.laterality))

metadata = file.read_all_metadata()
with open("metadata.json", "w") as outfile:
outfile.write(json.dumps(metadata, indent=4))`


But in fact, there is relevant data, about 40-50 sheets.

Can you use the data I uploaded last time to try and obtain the data in this file, and ultimately, how much data can be output？

**Comment by marksgraham** [comment]
Sorry I've actually not got the link anyone - could you email it to me? (my email is on my github profile)

**Comment by Oli4** [comment]
It might be possible to read such an e2e file with eyepy. This section in the documentation might help: https://medvisbonn.github.io/eyepy/formats/he_e2e/#access-other-data-stored-in-e2e-files

I could also have look myself.

**Comment by Jackiecs3** [comment]
> Sorry I've actually not got the link anyone - could you email it to me? (my email is on my github profile)
 

I have sent the data file via email to the address markgraham539@gmail.com, please check it. Thanks

**Comment by marksgraham** [comment]
It looks like there are some repeat scans in the file that get overwritten. I have added an option to not overwrite them. To access you will need to clone the repository and install by changing into the cloned directory and installing with `pip install .`

you can then use the new arg:

```python
fundus_images = (
    file.read_fundus_image(extract_scan_repeats=True)
)
```

**Comment by Jackiecs3** [comment]
> It looks like there are some repeat scans in the file that get overwritten. I have added an option to not overwrite them. To access you will need to clone the repository and install by changing into the cloned directory and installing with `pip install .`
> 
> you can then use the new arg:
> 
> ```python
> fundus_images = (
>     file.read_fundus_image(extract_scan_repeats=True)
> )
> ```
> 
> Curious if you've come accross this before @Oli4 ?

Continue using this instruction to obtain the latest code?
pip install git+[https://github.com/marksgraham/OCT-Converter](https://github.com/marksgraham/OCT-Converter%EF%BC%89)

**Comment by Oli4** [comment]
> It looks like there are some repeat scans in the file that get overwritten. I have added an option to not overwrite them. To access you will need to clone the repository and install by changing into the cloned directory and installing with `pip install .`
> 
> you can then use the new arg:
> 
> ```python
> fundus_images = (
>     file.read_fundus_image(extract_scan_repeats=True)
> )
> ```
> 
> Curious if you've come accross this before @Oli4 ?

Hi @marksgraham, 

thank you for the mention, I am aware that E2E files can contain multiple volumes or enfaces images. The Reader in eyepy should make them accessible. It also has an inspect method to give an overview of the files contents. 

```python 
from eyepy.io import HeE2eReader

with HeE2eReader("filename.E2E") as e2e_reader:
    print(e2e_reader.inspect(iterative=True)) # 
```

**Comment by Jackiecs3** [comment]
> > Continue using this instruction to obtain the latest code? pip install git+[https://github.com/marksgraham/OCT-Converter](https://github.com/marksgraham/OCT-Converter%EF%BC%89)
> 
> Yes that should work

HI mark

Firstly, thank you for your support. After running the code you corrected, I can read and retrieve all the data.

This project, through my personal use these days, I believe it is a very good and valuable project in the field of ophthalmology. At the same time, it also provided me with a lot of help, such as reading files in formats such as e2e and fds.

I will use this project for a long time. If I encounter any problems in the future, I will communicate with you in a timely manner. I sincerely hope that this project can become better and better.

Yesterday, through my own use, I encountered several problems.
1、I can obtain all the fundus data now, but can the number of files output in dicom format be consistent with images?
<img width="355" alt="image" src="https://github.com/marksgraham/OCT-Converter/assets/149683436/1c09136d-bdf6-40ce-b24d-ae9c780ab4bb">

2、About outputting dicom file label information.
oct-converter output dicom file tag

Regarding the label pixel spacing, it should appear in the level 1 directory, currently at level 3

<img width="941" alt="image" src="https://github.com/marksgraham/OCT-Converter/assets/149683436/58cd54b8-2547-4c69-8289-3189f2d5b644">
Correct example
<img width="828" alt="image" src="https://github.com/marksgraham/OCT-Converter/assets/149683436/1e1f57f4-15c0-45d9-83b3-bd2caa9480b3">

How is the content of this field generated?? At present, if measurements are made based on this parameter, the data is clearly incorrect! 300mm should be bigger than one eye
<img width="925" alt="image" src="https://github.com/marksgraham/OCT-Converter/assets/149683436/cae25dc4-e595-4e29-b210-4743cecaad74">

This is my own data, and the dicom tags comply with the specifications and the values are normal. The following figure shows the measurement results
<img width="913" alt="image" src="https://github.com/marksgraham/OCT-Converter/assets/149683436/2a148e7d-9fd2-4dd3-bf0d-f763a8e6c37f">

3、 About dicom tag
Correct example
Condition：
(0002,0003)  Media Storage SOP Instance UID   ==  (0008,0018)  SOP Instance UID
<img width="870" alt="image" src="https://github.com/marksgraham/OCT-Converter/assets/149683436/1253c135-0840-494c-863c-b27621b783c3">

current results
<img width="923" alt="image" src="https://github.com/marksgraham/OCT-Converter/assets/149683436/ddb626a1-0e64-479f-aa07-0ce5202763f6">

**Comment by marksgraham** [comment]
Hi,

Thanks for the feedback for the new dicom save feature. Could I ask you re-post these dicom issues on a new issue so its easier to keep track off?

**Comment by Jackiecs3** [comment]
> Hi,
> 
> Thanks for the feedback for the new dicom save feature. Could I ask you re-post these dicom issues on a new issue so its easier to keep track of?

ok
new issues
https://github.com/marksgraham/OCT-Converter/issues/128
