### ISSUE TITLE
Problem about read edb, sdb, and pdb files

### ISSUE THREAD

**Issue by Rex-Tang** [marksgraham/OCT-Converter#133]
Hi,
I am currently using the e2e  to read edb, sdb, and pdb files. I can retrieve an image from the sdb file, but I am unable to fetch data from the others, following the example provided by example.
Is the problem about files or any other issue?
I use oct_converter==0.6.2
The sample data can be found in https://drive.google.com/drive/folders/1-4wXFUaqJf9aAVCfGpesaXPvEUIvRxhC?usp=sharing
Thanks!!!

**Comment by marksgraham** [comment]
Hi there,

I think its a file issue. The reader was only designed to read `.e2e` files and has never been tested on `.sdb`/`.pdb` - I'm surprised it extracts any images at all from `.sdb`!

**Comment by Rex-Tang** [comment]
> Hi there,
> 
> I think its a file issue. The reader was only designed to read `.e2e` files and has never been tested on `.sdb`/`.pdb` - I'm surprised it extracts any images at all from `.sdb`!

Thanks a lot for your help @marksgraham!!!
All I have been told is that the file is in 'Heidelberg' format, so I am trying to use E2E to read it, seems like I need to find another way to solve it.
