### ISSUE TITLE
Exporting Contours (segmentation data) from E2E files

### ISSUE THREAD

**Issue by benjaminralex** [marksgraham/OCT-Converter#135]
Hey Mark!

Thanks always for the fantastic work!

I have an E2E file that has layer segmentations saved as contours. I can see it in the metadata (json), but can't access it.

Is there a way to actually get the contours? and overlay them on the images?

Cheers!

**Comment by marksgraham** [comment]
Hi,

You can view the contours overlaid on a volume by doing `volume.peek(show_contours=True)`. The actual code for the plotting is [here](https://github.com/marksgraham/OCT-Converter/blob/86839e12d08bd262b93f75ead06cc35942634f39/oct_converter/image_types/oct.py#L105-L116)
