### ISSUE TITLE
Saving .FDA files

### ISSUE THREAD

**Issue by Amritpal-001** [marksgraham/OCT-Converter#141]
I want to modify the segmentations stored and then save them back as ".fda" files. Thanks to this amazing package, I can read the files and get the segmentations. 

Any guidance on potential packages to use for saving ".fda" files would be extremely helpful.

Thanks.

**Comment by marksgraham** [comment]
Hi,

Glad you find it useful! I'm afraid we don't have any support for writing to .FDA files and I'm not aware of any packages that allow for this.
