### ISSUE TITLE
Single frame DCM file converted to 4000 pngs

### ISSUE THREAD

**Issue by yehudahkay** [marksgraham/OCT-Converter#144]
Hi,

I have a single frame DCM that gets converted to 4000 individual pngs rather than one file. 

Attaching the file. Thanks so much!

[1.2.826.0.1.3680043.214.52918855120256198526951573770024956810.zip](https://github.com/user-attachments/files/16573665/1.2.826.0.1.3680043.214.52918855120256198526951573770024956810.zip)

**Comment by yehudahkay** [comment]
It seems to me that this library was only intended to handle mutli frame dicom images but not single frame dicom images

**Comment by marksgraham** [comment]
The dicom support is quite limited in this library - I would really recommend pydicom for working with dicoms in general!
