### ISSUE TITLE
topcon dict IMG_OBS

### ISSUE THREAD

**Issue by RunningDongxu** [marksgraham/OCT-Converter#2]
Could I please ask what is the "IMG_OBS" in the fds.py? I am trying to access the fundus image from the topcon fda file.

**Comment by marksgraham** [comment]
IMG_OBS is the name of the file chunk that contains the fundus data. There are some examples of the different chunks and what they mean here, but modern .fds files seem to have slightly different naming: https://bitbucket.org/uocte/uocte/wiki/Topcon%20File%20Format

When you read the .fds file you should see a print out of all the chunks found in that file.

**Comment by RunningDongxu** [comment]
thank you for your reply, have you tried to access any .fda file? It seems the fda and fds have different file chunk.

**Comment by marksgraham** [comment]
Sorry I haven't tried to read .fda files - you may be able to read them
with the .fda code using the read_fundus function if you find the right
chunk? You could perhaps just try to read all the chunks in the .fda file?

**Comment by RunningDongxu** [comment]
No worries, thank you very much!
