### ISSUE TITLE
feature request - segmentation contours for e2e files?

### ISSUE THREAD

**Issue by macaodha** [marksgraham/OCT-Converter#26]
Hi there, 

Thanks for providing this codebase!

I was wondering if there were any plans to add functionality that could extract segmentation contours from E2E files? There is some example code for doing this (in C++) in [uocte](https://bitbucket.org/uocte/uocte/src/8ed70b7ecd5c92cbbfaac281fe090cf7136cba6d/src/io/load_heidelberg.cpp#lines-213).  

All the best,
Oisin

**Comment by marksgraham** [comment]
Hi Oisin,

This would be great to have but no plans to add at the moment, I just don't have the time to work on it. If you were interested on having a go at implementing and making a PR I'd welcome it though!

Best,
Mark

**Comment by marksgraham** [comment]
Hi,
Extraction of contours is now possible thanks to @jh88!
Best,
Mark
