### ISSUE TITLE
failed reading .fda file

### ISSUE THREAD

**Issue by RunningDongxu** [marksgraham/OCT-Converter#3]
Hi Mark,
I am trying to modify your fds code for reading my .fda file as below:
[.fda file](https://www.dropbox.com/s/89pbslod2j4238x/1000034_21011_0_0.fda?dl=0)
I can see the '@IMG_FUNDUS' from the chunkdict and I think it should contain the fundus image, however, I got the error "cannot reshape array of size 954595 into shape (3,2048,1536)", could you please help to get the fundus image from the .fda file, thank you very much!

**Comment by marksgraham** [comment]
Hi,
I've looked into this and can't get the fundus image from the file. It seems like the IMG_FUNDUS chunk isn't large enough to contain the image that should be there. I wonder if there actually is no fundus in the file - have you been able to verify independently (e.g. on a Topcon scanner) that the file contains a fundus image?

Also, is this Biobank data? If so, the corresponding .fds file will contain the fundus image, and my fds extraction code definitely works on those files.

**Comment by RunningDongxu** [comment]
Hi Mark, thank you for your reply, I just found the problem of reading the fundus image from the .fda, it is because the image was compressed so it needs to be decoded first. I think I will manage to read the fundus image from the .fda. 

Yes, it is from the Biobank, your code is excellent and really helps, thank you!

**Comment by marksgraham** [comment]
Hi Dongxu,

Glad my code is helping. If you manage to read the .fda file, would you be
able to feed back and let me know how you did it? Either a pull request
adding a .fda reader or just a snippet that I can use to add it myself
would be really helpful.

Thanks,
Mark

**Comment by RunningDongxu** [comment]
Hi Mark, I have added the .fda support and it requires the "pip install pylibjpeg" first. 
Thank you, 
Dongxu
