### ISSUE TITLE
Problem reading fda.read_oct_volume

### ISSUE THREAD

**Issue by antoniohupa** [marksgraham/OCT-Converter#30]
Hi Mark

Hope you're doing well. 
I've been using your code to open fda files from Topcon's OCT, but lately I'm having problems to open them as I usually did.
When I use the fda.read_oct_volume() I have the following issue: "ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject"

I really cannot see what is the problem cause the code is the same as always was but now it doesn't work ...
If I use the fda.read_oct_volume_2 I can open the file but only extracts 9 slices from the whole cube instead of 128 or 256...

By he way, I have some code pending to pull request to you. If you remember, we talk several times before. I have some code to extract from fda the eye, date of capture, and patient data (the latter if present in the file). Since 2016, patient data is not present in the file so I have to extract them from a file that is created at the time of the scan which is named "FILELIST".

Hope you can help me with that issue,
Thanks

Antonio

**Comment by antoniohupa** [comment]
Sorry, I put the whole text to the error below:



---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-f8412b521f10> in <module>
      1 file = './10028.fda'
      2 fda = FDA(file)
----> 3 fda.read_oct_volume()

~/opt/anaconda3/lib/python3.8/site-packages/oct_converter/readers/fda.py in read_oct_volume(self)
    108                 size = np.fromstring(f.read(4), dtype=np.int32)[0]
    109                 raw_slice= f.read(size)
--> 110                 slice = decode(raw_slice)
    111                 volume[:,:,i] = slice
    112         oct_volume = OCTVolumeWithMetaData([volume[:, :, i] for i in range(volume.shape[2])])

~/opt/anaconda3/lib/python3.8/site-packages/pylibjpeg/utils.py in decode(data, decoder, kwargs)
     37         available.
     38     """
---> 39     decoders = get_decoders()
     40     if not decoders:
     41         raise RuntimeError("No decoders are available")

~/opt/anaconda3/lib/python3.8/site-packages/pylibjpeg/utils.py in get_decoders(decoder_type)
    104         decoders = {}
    105         for entry_point in entry_points.values():
--> 106             decoders.update({
    107                 val.name: val.load() for val in iter_entry_points(entry_point)
    108             })

~/opt/anaconda3/lib/python3.8/site-packages/pylibjpeg/utils.py in <dictcomp>(.0)
    105         for entry_point in entry_points.values():
    106             decoders.update({
--> 107                 val.name: val.load() for val in iter_entry_points(entry_point)
    108             })
    109         return decoders

~/opt/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py in load(self, require, *args, **kwargs)
   2445         if require:
   2446             self.require(*args, **kwargs)
-> 2447         return self.resolve()
   2448 
   2449     def resolve(self):

~/opt/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py in resolve(self)
   2451         Resolve the entry point from its module and attrs.
   2452         """
-> 2453         module = __import__(self.module_name, fromlist=['__name__'], level=0)
   2454         try:
   2455             return functools.reduce(getattr, self.attrs, module)

~/opt/anaconda3/lib/python3.8/site-packages/openjpeg/__init__.py in <module>
      2 
      3 from ._version import __version__
----> 4 from .utils import decode, decode_pixel_data, get_parameters

~/opt/anaconda3/lib/python3.8/site-packages/openjpeg/utils.py in <module>
      5 import warnings
      6 
----> 7 import _openjpeg
      8 
      9 

~/opt/anaconda3/lib/python3.8/site-packages/openjpeg/_openjpeg.pyx in init _openjpeg()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by marksgraham** [comment]
Hi Antonio,

What git commit are you using? I recently updated the .fds code and I can't see how I could affect this but maybe it has in some way - would be good to check that you are indeed using exactly the same commit you were using when it lasxt worked for you.

Looking forward to your pull request!

Mark

**Comment by antoniohupa** [comment]
Hi Mark

It is intriguing but I tried the old code that I forked in December 2020 (or earlier) and it doesn't work... To discard it could be an issue with my computer, could you try if you can run the code to extract fda files without problems?

**Comment by marksgraham** [comment]
Hi - 
The code works for me on the fda I downloaded from here - can you try it?
https://biobank.ndph.ox.ac.uk/ukb/refer.cgi?id=31
Of course can try on any of your .fdas if you are able to share them but I suspect you may not due to data privacy

**Comment by antoniohupa** [comment]
Hi

Yes I also tried with that file you propose in order to discard a problem with my fda files and didn't work neither... Some people say it is a problem with numpy but I have uninstall and reinstall and continues raising the same error...
What version of the packages required are you using?

**Comment by antoniohupa** [comment]
Thanks, I'll set up a new virtual environment and I'll come back to you. 

Thanks again Mark

**Comment by antoniohupa** [comment]
Hi Mark

I've set up a new environment and the code seems to work right as always.. I'm gonna be doing some more tests but at the moment everything's ok

Thanks again Mark

Antonio

**Comment by marksgraham** [comment]
Great - let me know if there are further issues and we can revisit
