### ISSUE TITLE
Pixel distribution in fda files

### ISSUE THREAD

**Issue by antoniohupa** [marksgraham/OCT-Converter#32]
Hi Mark

Hope you're doing well.
These days I've been extracting some fda files to png and I've notice that the program extracts all the images with the same distribution of pixels so seems an artifact when compared to the images extracted directly from the device.
Do you know if there is some parameter in the code which I could tune to modify that distribution?

Here's a link where you can see the comparison of the distribution of pixel from oct-converter (at left) and extracted from the device.

[https://drive.google.com/file/d/17xFnlKed8gyWeeFzJvqknOkXIXVM3_hT/view?usp=sharing](url)

Thanks in advance
Regards!
A

**Comment by marksgraham** [comment]
Hey,

Thats an interesting observation - are you looking at the data in the numpy array as it comes out the scanenr? Or after the data has been saved to an image or video file?

**Comment by antoniohupa** [comment]
Hi Mark

Both images (the ones extracted with your code and the ones extracted from the scanner) are saved in png.

**Comment by marksgraham** [comment]
Could you look at the distribution of the data extracted into a np array, before it is saved into png? I'm wondering if the process of converting the image to a png normalises the data somehow

**Comment by antoniohupa** [comment]
Hi Mark

Looking at the numpy arrays extracted from oct volume I've noticed that they follow the same distribution as I commented earlier. But this is only happening with my fda files but not with the demo fda file downloaded from the UK biobank. For the later, the distribution of pixels is the same as the one extracted from the instrument in jpeg... Maybe it is an issue of the instrument itself and not of the code....
