### ISSUE TITLE
Conversion for Heidelberg Spectralis??

### ISSUE THREAD

**Issue by steffejr** [marksgraham/OCT-Converter#41]
Hello all,
I am working with file types of:
.pdb
.edb
.sdb
.mdb

Is there anyone working on the conversion/reading of these file types? If not I can get started with it and would welcome pointers.
Thank you,
Jason

**Comment by camlloyd** [comment]
These look like the files that come from _Database > Archive Images..._ rather than right-clicking an image and selecting _Export > as E2E_

and I am always interested in taking a look when I have some spare time.
