### ISSUE TITLE
pdb, sdb, edb file format to image

### ISSUE THREAD

**Issue by niloofarAzari** [marksgraham/OCT-Converter#43]
Hi
I have some folders of pdb, sdb, and edb files which are outputs of the Heidelberg system. Each folder is related to a patient and may contain different types of retinal images such as fundus or fluorescein angiography or OCT.
I want to convert these files to images.
I wonder if your code can do this for me?

**Comment by camlloyd** [comment]
Hi @niloofarAzari,
#41 is a good place to start.
Thanks! 🎄

**Comment by niloofarAzari** [comment]
Thank you
