### ISSUE TITLE
".fromstring" method in e2e.py generates warnings with possible downstream consequences

### ISSUE THREAD

**Issue by orenavram** [marksgraham/OCT-Converter#50]
Hi there,

I am using your lovely e2e reader with Python 3.9. Some of the arrays I am trying to load are ragged (and raise a warning) so I also used the following to inspect these ragged arrays:
import warnings
warnings.filterwarnings("error")

That made me come across another warning:
`The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead`

generated by line 252 in the e2e.py file:
`raw_volume = np.fromstring(f.read(image_data.height * image_data.width), dtype=np.uint8)`

According to [https://stackoverflow.com/questions/60320840/numpy-fromstring-deprecated-use-frombuffer-instead](url) it seems like the loading should be done by np.frombuffer (instead of np.fromstring). I edited the source code locally and it seems to indeed prevent this warning. I don't know if there are consequences for these fromstring warnings but it might be something you want to check on the next versions.

Regards,
Oren

**Comment by Dbrown411** [comment]
Oren,

My guess would be that this shouldn't have any impact on reading the .E2Es one way or the other - I don't believe that the files should have any unicode characters. But, obviously it is best to remove deprecated function calls whenever possible. I could look at it further, but if the change is small and its working for you locally, I'm sure Mark would appreciate you creating a pull request.

Dillon

**Comment by marksgraham** [comment]
Hi there,

Agree it would be nice to stop the error - would love a pull request if you had tiem!

Mark

**Comment by orenavram** [comment]
Sure. Just did.
Thanks

**Comment by marksgraham** [comment]
Many thanks!
