### ISSUE TITLE
fda.read_oct_volume gives No decoders are available error

### ISSUE THREAD

**Issue by YaseminTurkan** [marksgraham/OCT-Converter#52]
Hi Mark,

Thanks a lot for the library. I will be using it a lot for my Ph D. Thesis

I am trying to read UKBiobank file in fda format.  I got the following error:
"No decoders are available error"

I nhave debuf-gged the code 
in function read_oct_volume (self) there is a function called
slice = decode (raw_slice) which calls from pylibjpeg  
in the decode function decoders = get_getcoders() returns empty set. I have installed all the files.

Am I missing something?  
Thanks again for your great support for the library
Best Yasemin

**Comment by marksgraham** [comment]
Hi,

Could you tell me what version of Python and pylibjpeg you're using?

**Comment by YaseminTurkan** [comment]
python 3.7.9
pylibjpeg 1.4.0

**Comment by marksgraham** [comment]
Any chance you can send me an example of the .fda file this fails on? Or check whether it works for you using the example .fda file you can download from here: https://biobank.ndph.ox.ac.uk/ukb/refer.cgi?id=31

**Comment by YaseminTurkan** [comment]
it gives the same error when I test with the data in your link. My downloaded UK Biobank files are in the attachment
[UKBiobank.zip](https://github.com/marksgraham/OCT-Converter/files/8470172/UKBiobank.zip)

**Comment by marksgraham** [comment]
Hm these all work fine for me. What OS are you using? Can you send me the full output of `pip list`?

**Comment by YaseminTurkan** [comment]
I found the issue, it has been with the environment variables. I needed to reboot my PC after the installation of the libraries. (By the way, I was running on Windows 10)

Thanks a lot for your all help.  Very much appreciated. I will be using your library a lot during my Ph. D. Thesis :)
