### ISSUE TITLE
Get layer positions from bscan metadata 

### ISSUE THREAD

**Issue by jh88** [marksgraham/OCT-Converter#66]
Hi Mark,

You added `bscan_metadata` to the e2e reader in the latest commits. I think each slice of layer segment has one corresponding `bscan_metadata`.  I was wondering how can I use `posX1`, `posY1`, `posX2`, `posY2` etc to find the locations of these layers on the fundus image?

Thank you,
Hua

**Comment by marksgraham** [comment]
Hi Hua,

I'm not sure if the .e2e files contain information about how these coordinates relate to the coordinate frame of the fundus images - do you have any reason to believe they do?

One thing you could do is create an en-face image from the OCT scan using the get_projection() method - the layer coordinates will be in the same coordinate space as this projection. But then you would need to do some image registration between the en-face and a fundus to then project these coordinates into the space of the fundus.

Best,
Mark

**Comment by panglaoshu** [comment]
Mark, I think the E2E file must contain such information. In the heidelberg viewer, each b-scan is directly matched to the corresponding location on the infrared fundus image. This is very helpful to see which OCT feature correspond to which fundus feature. I'm attaching a couple of examples. It would be real nice if we could do the following:
- display the extracted b-scans and the extracted fundus in a way similar to the heidelberg viewer, 
- do the same but using a different type of fundus image (eg: color, FAF, etc.). This would required to first manually register that other type of fundus image on top of the extracted fundus

![ScreenHunter 2996](https://user-images.githubusercontent.com/30542398/190870216-f4c24c51-84c4-4883-a480-aed3fc9b3887.jpg)

![ScreenHunter 2997](https://user-images.githubusercontent.com/30542398/190870214-85f0b5f3-917d-4bc9-9ae7-1092b3b2128f.jpg)

**Comment by Oli4** [comment]
The Heyex VOL and XML exports contains theses positions and I would also expect the E2E to contain these positions. I support VOL and XML in the eyepy Package and also plan to add E2E. 

With regard to the visualization, this is already possible with eyepy. You can plot the localizer with arbitrary b-scan positions as an overlay and also the B-scans. You would only have to assemble it into one figure. The documentation is still work in progress but if you have any specific questions let me know.

**Comment by panglaoshu** [comment]
Thanks Olivier. This works nicely. Is there a way in eyepy to also display the green lines in the IR image?

**Comment by Oli4** [comment]
If you have an EyeVolume `ev` object you can plot the NIR with bscan positions like `ev.plot(bscan_positions=True)`. You can also provide a list of indices to plot only the respective B-scans. Indices start at 0 and the 0th B-scan is the bottom one in the NIR.

**Comment by panglaoshu** [comment]
I'll try that later today Olivier, thanks! When we're at it, do you have a good way to extract a vast majority of metadata from E2E files without going through XML? I have hundreds of E2E files that I'd like to automatically rename based on name, date of visit, and contents of the E2E (eg: IR, BAF/FAF, OCT, etc)

**Comment by Oli4** [comment]
Maybe we should shift this discussion to the eyepy issues because they seem to be a bit offtopic here. Unfortunatelly my E2E parser isn't ready yet.

**Comment by marksgraham** [comment]
Afraid I can't work out atm where to find this information in the E2E files. Maybe if @Oli4 manages to get it into their e2e reader i'll pinch the code :P  @panglaoshu you can use my tool to rename based on name and acquistion date but it doesn't currently output contents of the e2e. (e.g. IR, FAF)
