### ISSUE TITLE
StreamError when converting .oct files

### ISSUE THREAD

**Issue by gxg2002cn** [marksgraham/OCT-Converter#67]
Dear Mark,
Thanks a lot for developing OCT-Converter. 
I wish to extract the photo from some .oct files (an example attached), but met the StreamError. I wonder if there is any suggestion on solving the problem? Many thanks!

Best regards,
Xiaogang

![image](https://user-images.githubusercontent.com/37469970/192285110-1092ebe2-76aa-444e-bd20-c9c2a055d562.png)

[Default_0002_Mode2D.zip](https://github.com/marksgraham/OCT-Converter/files/9646464/Default_0002_Mode2D.zip)

**Comment by marksgraham** [comment]
Hi,

First things first - are you sure it's a .oct file from a Bioptigen scanner?

Mark

**Comment by gxg2002cn** [comment]
Hi Mark,

Thanks for your remainder and sorry to bother. Please ignore my issue.

I just confirmed the .oct file used Thorlabs OCT imaging systems and as output from ThorImage®OCT (https://www.thorlabs.de/newgrouppage9.cfm?objectgroup_id=7982). 

I managed to import it into ImageJ following their instruction at (https://www.thorlabs.de/thorcat/MTN/MTN020880-D03.pdf) page 100-101. 

Thank you again!

Xiaogang
