### ISSUE TITLE
Unable to decode the data

### ISSUE THREAD

**Issue by Hcayirli** [marksgraham/OCT-Converter#69]
### I have various fda files. While running the script I am getting an error in some files. Below are oct_header information and error statuses.

![Results](https://user-images.githubusercontent.com/98592466/199657192-8a618682-d3ae-4b35-830d-d6f236a8bfde.png)

### The error received and the place where the error was received are given below.

![Error](https://user-images.githubusercontent.com/98592466/199657693-26ad728c-d38f-4b4b-873c-15e2c1700ff9.png)

### What can be the problem? Do you have a solution suggestion?

**Comment by marksgraham** [comment]
Hi,

Are you able to check if this happens immediately (i.e. on the first slice) here:
https://github.com/marksgraham/OCT-Converter/blob/2ef8ba3eb13e27d0ad7fa077a86513297d7b646c/oct_converter/readers/fda.py#L112
I'm wondering if it perhaps manages to decode most the slices OK

Another thought is you might want to try the read_oct_volume_2() method that doesn't rely on jpeg decoding - perhaps that will work for you?
https://github.com/marksgraham/OCT-Converter/blob/2ef8ba3eb13e27d0ad7fa077a86513297d7b646c/oct_converter/readers/fda.py#L122

**Comment by marksgraham** [comment]
Going to close due to inactivity, let me know if you want to revisit
