### ISSUE TITLE
How to get OCTA from fda file

### ISSUE THREAD

**Issue by pomeloyy** [marksgraham/OCT-Converter#70]
Hi Mark,
Hope you are doing well.
Recently I have been collecting some fda files which include OCTA images.  I guess the useful information should be stored in these two chunks '**@PARAM_ANGIOGRAPHY**' and  '**IMG_ANGIOGRAPHY_02**'. 

_**Have you tried extracting the OCTA directly from the fda file before, just like extracting OCT and fundus?**_
![image](https://user-images.githubusercontent.com/79888826/200301096-8d199fa7-afcd-40da-9b09-82296b3c333d.png)

Thanks in advance
Regards!

**Comment by marksgraham** [comment]
Hi,

I've never got my hands on any FDA angio data so I haven't tried it out. If you wanted to have a go, you can try changing this function to read the IMG_ANGIOGRAPHY_02 field - you might get lucky and find it just works:
https://github.com/marksgraham/OCT-Converter/blob/2ef8ba3eb13e27d0ad7fa077a86513297d7b646c/oct_converter/readers/fda.py#L122

As an alternative, if you're able to share data and want me to take a look then get in touch via my email - though I might be slow to get round to it!

Mark
