### ISSUE TITLE
fda example bug

### ISSUE THREAD

**Issue by wx-guyue** [marksgraham/OCT-Converter#71]
Dear Authors,

**demo_fda_extraction.py** cannot run.
"No decoders are available"

Could you fix this? Thanks a lot!

**Comment by marksgraham** [comment]
What OS are you running? I've seen this before and it is usually due to the requirement not being correctly installed, often on windows.

**Comment by wx-guyue** [comment]
Thank you very much Mark!
My os is Linux. Below are the errors. Do you have any idea how to fix it?  

`oct_fda.read_oct_volume()

oct_converter/readers/fda.py in read_oct_volume(self)
    113                 size = np.fromstring(f.read(4), dtype=np.int32)[0]
    114                 raw_slice = f.read(size)
--> 115                 slice = decode(raw_slice)
    116                 volume[:, :, i] = slice
    117         oct_volume = OCTVolumeWithMetaData(

pylibjpeg/utils.py in decode(data, decoder, kwargs)
     38     decoders = get_decoders()
     39     if not decoders:
---> 40         raise RuntimeError("No decoders are available")
     41 
     42     if isinstance(data, (str, os.PathLike)):

RuntimeError: No decoders are available`

**Comment by marksgraham** [comment]
Could you try to install oct-converter and all its requirements in a fresh virtual environment

**Comment by wx-guyue** [comment]
Thank you Mark!

I created a fresh env, and installed oct-converter. But still the same error "No decoders are available".

I will do a search to fix this bug, and will let you know once figure out a solution.

**Comment by marksgraham** [comment]
You might be able to fix it by installing all the ptlibjpeg requirements as detailed here:
https://github.com/pydicom/pylibjpeg
