### ISSUE TITLE
Cannot read Zeiss Dicom OCTA scans

### ISSUE THREAD

**Issue by xycyx** [marksgraham/OCT-Converter#78]
Thanks for your work on the Zeiss Dicom format, now I can read the dicom files from Zeiss SD-OCT Macular Cube structural scan (512x128, 200x200 on 6x6mm).
However, I cannot read the Zeiss SD-OCTA scans, which size 350x350x1024 for 6x6mm, and size 245x245x1024 for 3x3mm. Looks like no JP2 header "\x00\x00\x00\x0C" in the PixelData.
I guess they might change the way to obfuscate the data but still use the JPEG2000.

Have you tried this on the SD-OCTA dicom file? 

> C:\ProgramData\Anaconda3\lib\site-packages\pydicom\charset.py:471: UserWarning: Found unknown escape sequence in encoded string value - using encoding iso8859
>   warnings.warn(msg + f" - using encoding {encodings[0]}")
> 
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-20-d991a437facd>", line 4, in <module>
>     oct_volumes, fundus_volumes = img.read_data()  # returns a list OCT and fudus images
>   File "C:\ProgramData\Anaconda3\lib\site-packages\oct_converter\readers\zeissdicom.py", line 93, in read_data
>     unscrambled_frame = self.unscramble_frame(scrambled_frame)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\oct_converter\readers\zeissdicom.py", line 146, in unscramble_frame
>     raise ValueError("No JP2 header found in the scrambled pixel data")
> ValueError: No JP2 header found in the scrambled pixel data

**Comment by marksgraham** [comment]
Hi,

I've never had any OCTA data to try with. Would you be able to share a scan with me (preferably over email)? If so I can take a look

**Comment by xycyx** [comment]
I have sent some examples to you by email. Thank you.

**Comment by marksgraham** [comment]
Hi @xycyx,

I've attempted a fix. Can you test the fix by installing this PR (it might have to be on a fresh virtualenv):

`pip install git+https://github.com/marksgraham/OCT-Converter.git@refs/pull/81/merge`

and let me know if it works?

**Comment by xycyx** [comment]
It works for SD-OCTA 3x3 and 6x6 scans. Thank you for the updates.

Just got the warning 

> : UserWarning: Found unknown escape sequence in encoded string value - using encoding iso8859
>   warnings.warn(msg + f" - using encoding {encodings[0]}")
> 
when I run this:
`oct_volumes, fundus_volumes = img.read_data()  # returns a list OCT and fudus images`
But that doesn't matter.
