### ISSUE TITLE
Commit Request

### ISSUE THREAD

**Issue by FurkyT** [marksgraham/OCT-Converter#88]
Made Improvments On fda_testing.py, oct.py, fda.py

- There is a warning when writing video from bscans says:
"Lossy conversion from float64 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning."

- When testing the files with fda_testing.py if an image chunk is not in fda file methods raise Value Error and 
the code terminating for preventing that the if condition in image methods updated as other methods. Like if an
image chunk is not in fda file the method print the info and return None. But this cause another error which is terminate
the code on testing side the error come from save function and says "None type object has no attribute save" for
prevent that an if statement added on fda_testing.py checking if image data exist or None.

- I made the changes you want on the fda.py now there is only one method for making the json from other chunks datas

**Comment by marksgraham** [comment]
Thanks for this - will try to get round to reviewing soon
