### ISSUE TITLE
Zeiss Cirrus 6000 issues

### ISSUE THREAD

**Issue by UpwardTrajectory** [marksgraham/OCT-Converter#9]
When working with either dicom (preferred) or \*.img files (hopefully won't have to) from a "Carl Zeiss Cirrus 6000" machine, the code here is unable to parse the image, and instead throws errors. I have two different formats (\*.dcm, \*.img) available and also two different TransferSyntaxUIDs, but can't get any options to work.

with dicom:

```
from oct_converter.readers import Dicom

for i, filepath in fpaths.items():
    try:
        file = Dicom(filepath)
        oct_volume = file.read_oct_volume()  # returns an OCT volume with additional metadata if available
        print(i)
    except Exception as e:
        print(f"#{i} failed: {e}")
```

>0 failed: Unable to convert the pixel data: one of Pixel Data, Float Pixel Data or Double Float Pixel Data must be present in the dataset
1 failed: No matching JPEG 2000 format found
2 failed: Unexpected tag '(ab8f, 7b89)' when parsing the Basic Table Offset item.
3 failed: Unexpected tag '(1eab, 3f83)' when parsing the Basic Table Offset item.
4 failed: Unexpected tag '(ab3a, b796)' when parsing the Basic Table Offset item.
5 failed: Unable to convert the pixel data: one of Pixel Data, Float Pixel Data or Double Float Pixel Data must be present in the dataset
6 failed: No matching JPEG 2000 format found
7 failed: Unexpected tag '(4a27, c7c7)' when parsing the Basic Table Offset item.
8 failed: Unexpected tag '(9bea, 539b)' when parsing the Basic Table Offset item.
9 failed: Unexpected tag '(9d70, b305)' when parsing the Basic Table Offset item.
10 failed: Unable to convert the pixel data: one of Pixel Data, Float Pixel Data or Double Float Pixel Data must be present in the dataset
11 failed: No matching JPEG 2000 format found
12 failed: Unexpected tag '(87ad, ae02)' when parsing the Basic Table Offset item.
13 failed: Unexpected tag '(3ef9, c56e)' when parsing the Basic Table Offset item.
14 failed: Unexpected tag '(93ca, 9a6a)' when parsing the Basic Table Offset item.
15 failed: Unable to convert the pixel data: one of Pixel Data, Float Pixel Data or Double Float Pixel Data must be present in the dataset
16 failed: No matching JPEG 2000 format found
17 failed: Unexpected tag '(e6b5, 94bc)' when parsing the Basic Table Offset item.
18 failed: Unexpected tag '(55a2, 7aa4)' when parsing the Basic Table Offset item.
19 failed: Unexpected tag '(108a, 99c8)' when parsing the Basic Table Offset item.
20 failed: unsupported operand type(s) for //: 'str' and 'str'
21 failed: No matching JPEG 2000 format found
22 failed: No matching JPEG 2000 format found
23 failed: Unexpected tag '(d484, c455)' when parsing the Basic Table Offset item.
24 failed: Unexpected tag '(9ab2, 6eb9)' when parsing the Basic Table Offset item.
25 failed: Unexpected tag '(f54c, 1a7f)' when parsing the Basic Table Offset item.
26 failed: Unexpected tag '(71a0, 48eb)' when parsing the Basic Table Offset item.
27 failed: Unable to convert the pixel data: one of Pixel Data, Float Pixel Data or Double Float Pixel Data must be present in the dataset
28 failed: No matching JPEG 2000 format found
29 failed: No matching JPEG 2000 format found
30 failed: No matching JPEG 2000 format found
31 failed: Unexpected tag '(f24f, eb93)' when parsing the Basic Table Offset item.
32 failed: Unexpected tag '(e60c, 05ba)' when parsing the Basic Table Offset item.
33 failed: Unexpected tag '(0253, 5d4a)' when parsing the Basic Table Offset item.
34 failed: Unexpected tag '(88ba, f184)' when parsing the Basic Table Offset item.
35 failed: Unable to convert the pixel data: one of Pixel Data, Float Pixel Data or Double Float Pixel Data must be present in the dataset

In case it's helpful here are the `TransferSyntaxUID` specifications for these .dcm files (metadata reads fine in PyDicom, but not the image)
> 00  ->  1.2.840.10008.1.2.1
01  ->  1.2.840.10008.1.2.4.90
02  ->  1.2.840.10008.1.2.4.90
03  ->  1.2.840.10008.1.2.4.90
04  ->  1.2.840.10008.1.2.4.90
05  ->  1.2.840.10008.1.2.1
06  ->  1.2.840.10008.1.2.4.90
07  ->  1.2.840.10008.1.2.4.90
08  ->  1.2.840.10008.1.2.4.90
09  ->  1.2.840.10008.1.2.4.90
10  ->  1.2.840.10008.1.2.1
11  ->  1.2.840.10008.1.2.4.90
12  ->  1.2.840.10008.1.2.4.90
13  ->  1.2.840.10008.1.2.4.90
14  ->  1.2.840.10008.1.2.4.90
15  ->  1.2.840.10008.1.2.1
16  ->  1.2.840.10008.1.2.4.90
17  ->  1.2.840.10008.1.2.4.90
18  ->  1.2.840.10008.1.2.4.90
19  ->  1.2.840.10008.1.2.4.90
20  ->  1.2.840.10008.1.2.4.90
21  ->  1.2.840.10008.1.2.4.90
22  ->  1.2.840.10008.1.2.4.90
23  ->  1.2.840.10008.1.2.4.90
24  ->  1.2.840.10008.1.2.4.90
25  ->  1.2.840.10008.1.2.4.90
26  ->  1.2.840.10008.1.2.4.90
27  ->  1.2.840.10008.1.2.1
28  ->  1.2.840.10008.1.2.4.90
29  ->  1.2.840.10008.1.2.4.90
30  ->  1.2.840.10008.1.2.4.90
31  ->  1.2.840.10008.1.2.4.90
32  ->  1.2.840.10008.1.2.4.90
33  ->  1.2.840.10008.1.2.4.90
34  ->  1.2.840.10008.1.2.4.90
35  ->  1.2.840.10008.1.2.1

for the IMG version, all of the errors fall into some form of `cannot reshape array of size _____ into shape (1024,512,128)` where the _____ is either 5242880 or 2097152

**Comment by UpwardTrajectory** [comment]
pre-emptive apology for accidentally "commenting" or referencing all the other issues for this very helpful library. My copy-paste code used to have "#X failed", and I didn't realize that would auto-link other issues on GitHub.

**Comment by marksgraham** [comment]
Hi there,

Have you had any luck extracting the Dicom data from any other software, or with viewing it in a Dicom viewer? The Dicom reader is very simple here, it just uses Pydicom behind the hood. So if you can't read the file using Pydicom or any other reader, then this is likely a problem beyond the scope of this codebase.

Regarding the .img files, I think I can help. The code is very simple and expects 128 slices, each 1024 x 512 - this was in keeping with the only Zeiss data I had when I wrote that reader. It seems your cubes have different numbers of slices: 2097152/(1024\*512) = 4, and  5242880/(1024\*512) = 10.  Could you try replacing the following line in `readers/img.py`

```
volume = volume.reshape((1024, 512, 128), order='F'
```
 with something like:

```
num_slices = len(volume)
volume = volume.reshape((1024, 512, num_slices), order='F')
```
and let me know what happens?

**Comment by UpwardTrajectory** [comment]
That fix worked great for `IMG` files! Thank you! I propose adapting lines 21->24 of https://github.com/marksgraham/OCT-Converter/blob/master/oct_converter/readers/img.py with this:
```
with open(self.filepath, 'rb') as f:
        volume = np.frombuffer(f.read(), dtype=np.uint8)  # address numpy depreciation warning
        num_slices = len(volume) // (1024*512)
        volume = volume.reshape((1024, 512, num_slices), order='F')   
        shape = volume.shape
```
Do you want to maintain being the sole contributor (it was your code, after all), or would you rather not deal w/ it and I can send a pull request?

Also, do you know of any way to find the method used to convert from the DICOM bytes stored in PixelData -> `IMG` files? I would love to remain in the DICOM ecosystem if possible, but getting IMGs to work is still great.

**Comment by UpwardTrajectory** [comment]
Also, I forgot to address this:
>Have you had any luck extracting the Dicom data from any other software, or with viewing it in a Dicom viewer?
PyDicom can view & edit the meta data just fine, but the PixelData hasn't worked on any environment setup that I've tried. (Also, when I attempt to save after editing away the PHI, PyDicom fails, due to the PixelData being "unencapsulated"). 
```
ValueError: (7FE0,0010) Pixel Data has an undefined length indicating that it's compressed, but the data isn't encapsulated as required.
```

GUI-based viewers haven't worked either, and when I called Zeiss customer support, they implied the only option was to remotely connect to the very expensive OCT machine as a "review station computer", but that just sounds like proprietary vendor-lock, to me.

**Comment by marksgraham** [comment]
Hi there,

A pull request would be ideal, thank you!

I'm afraid I don't know how to find out how to turn the DICOM bytes into image files. UOCTE, which I have got most the file descriptors from, had this to say about the old zeiss format [on their wiki](https://bitbucket.org/uocte/uocte/wiki/Zeiss%20File%20Format):

> Zeiss file format was discontinued. It uses an excellent obfuctation strategy: The image data is probably JPEG2000 encoded (there is an JPEG end-of-stream marker at the end), but there is no header. Guessing the header is tedious (one would need to know the quatization used) to the point of being infeasible.

I think this refers their old proprietary format, but it seems they used to be very invested in making it difficult to access their imaging data without their hardware, and appears they have done something similar with their DICOM data. A quick google reveals some references to their DICOM data being encrypted: e.g [this](https://www.reddit.com/r/dicom/comments/46elm7/can_a_company_claim_it_is_dicom_compatible_but/).
