### ISSUE TITLE
.opt Files

### ISSUE THREAD

**Issue by FurkyT** [marksgraham/OCT-Converter#92]
Hi everyone, 
Is there anyone who ever work with .opt files.

**Comment by marksgraham** [comment]
Do you know what scanner manufacturer the files come from?

**Comment by FurkyT** [comment]
Yes, from optopol

**Comment by camlloyd** [comment]
@FurkyT are you able to share an example file?

**Comment by FurkyT** [comment]
> Hm on a quick scan I can't find anything about how to read them online. If you manage to find something would be great to incorporate it into the package

I also looked it up but there is no explanation about file format on internet, I may have decode it by myself but it will take a lot of time and for now I dont have that time but if I do I will add it in here.

**Comment by FurkyT** [comment]
> @FurkyT are you able to share an example file?

I have an example file but unfortunately I cant share it.

**Comment by marksgraham** [comment]
Closing as we can't work on this without any info on the .opt spec
