### ISSUE TITLE
Parse segmentation from fda files

### ISSUE THREAD

**Issue by drombas** [marksgraham/OCT-Converter#94]
Hi and thanks for the tool.

I am trying to parse segmentation data from fda files to extend [eyepy](https://github.com/MedVisBonn/eyepy/discussions/11).

I believe the segmentation is stored in @CONTOUR_INFO chunks (one per layer).

I've noticed that the [`read_any_info_and_make_dict`](https://github.com/marksgraham/OCT-Converter/blob/155df23327065214013036055a4d91d791998f8b/oct_converter/readers/fda.py#LL158C11-L158C55) cannot be used to retrieve the segmentation of all layers as they share the same name and key in the dictionary.

What do you think about adding a `read_segmentation()` method to `FDA` class ? I can do it myself if it sounds good.

**Comment by marksgraham** [comment]
Hi @drombas 

Sounds like a good idea to me. Thanks for working on this!
