### ISSUE TITLE
'ascii' codec can't decode byte 0xff in position 8: ordinal not in range(128)

### ISSUE THREAD

**Issue by benjaminralex** [marksgraham/OCT-Converter#98]
Upon trying to open an E2E file, I get the following error: 

`'ascii' codec can't decode byte 0xff in position 8: ordinal not in range(128)`

What is the most likely cause of this? Thanks!

**Comment by marksgraham** [comment]
Hi,

Haven't come across this .e2e error before and it suggests its having trouble early on, reading the main directory structure. One thing you could try is to read it using [eyepy](https://github.com/MedVisBonn/eyepy) which has a different .e2e reader and may fare better. Alternatively, if you're able to share the file with my I could have a look.

**Comment by benjaminralex** [comment]
Hi Mark, I have not unfortunately.

Thank you for the follow up. Would greatly appreciate a fix!

Thank you!

**Comment by marksgraham** [comment]
Could you try out the update on the main branch?

**Comment by benjaminralex** [comment]
That seems to do the trick! I tested on a few images, but it maybe fail on a wider set of samples. Thanks a lot! Much appreciated.
